name: Check for broken links

on:
  push:
  pull_request:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker 🔗
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          fail: true
          args: >-
            --exclude-path README.md
            --exclude-path CUSTOMIZE.md
            --exclude-path INSTALL.md
            --exclude-path FAQ.md
            --exclude-path AGENT.MD
            --exclude-path CONTRIBUTING.md
            --exclude-path .github
            --exclude-path _pages
            --exclude-path _includes
            --exclude-path _layouts
            --exclude-path _regio
            --exclude-path llms.txt
            --exclude-path llms-full.txt
            --verbose
            --no-progress
            './**/*.md'
            './**/*.html'
